### ISSUE TITLE
Games do not launch from GOG Galaxy

### ISSUE THREAD

**Issue by lbacud** [tkashkin/GOGWrapper#1]
GOG changed the command to launch games to /command=launchGame

**Comment by tkashkin** [comment]
Works on Galaxy 1.2.26.
`/command=launch` still opens game page, `/command=launchGame` does nothing.
There's no command to directly launch a game afaik.

Currently games are launched in a very hacky way (simulating click in button location).
Maybe you have DPI scaling enabled and button is in different location?

**Comment by lbacud** [comment]
My mistake. The command is "/command=runGame"

For example, the launch command I use for Witcher 3 is "C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe" /gameId=1495134320 /command=runGame /path="C:\GOG Games\The Witcher 3 Wild Hunt GOTY"

**Comment by tkashkin** [comment]
It works! Was this command added recently? I couldn't find it before.

**Comment by lbacud** [comment]
It was mentioned in a [bug report for the Playnite launcher](https://github.com/JosefNemec/Playnite/issues/158). So all we need to do is find the path of the game itself.
