### ISSUE TITLE
How to install / use GOGWrapper

### ISSUE THREAD

**Issue by Roukard** [tkashkin/GOGWrapper#2]
So, I'm totally new at this.  I've downloaded GOGWrapper-master.zip.  How do I install, and use it?  Please advise.  Thanks!

**Comment by tkashkin** [comment]
Download compiled binary instead of source code. You can find it on the [releases](https://github.com/tkashkin/GOGWrapper/releases) page.

**Comment by Roukard** [comment]
Thanks!
